# Generated by Django 3.0.7 on 2020-09-15 12:44

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObservationByGrid',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('pm1_0', models.FloatField(default=0.0)),
                ('pm2_5', models.FloatField(default=0.0)),
                ('pm10_0', models.FloatField(default=0.0)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326, verbose_name='geom')),
                ('username', models.CharField(max_length=50, verbose_name='username')),
            ],
            options={
                'db_table': 'api_observation_by_grid',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pm1_0', models.FloatField(default=0.0)),
                ('pm2_5', models.FloatField(default=0.0)),
                ('pm10_0', models.FloatField(default=0.0)),
                ('date', models.DateField(verbose_name='date')),
                ('time', models.TimeField(verbose_name='time')),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='geom')),
                ('username', models.CharField(max_length=50, verbose_name='username')),
            ],
            options={
                'verbose_name': 'observation',
                'verbose_name_plural': 'observations',
            },
        ),
    ]
