# Generated by Django 3.0.7 on 2020-06-25 13:23

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('observationId', models.IntegerField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(verbose_name='datetime')),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='geom')),
                ('altGPS', models.FloatField(default=0.0, verbose_name='altGPS')),
                ('temp', models.FloatField(default=0.0, verbose_name='temp')),
                ('hum', models.FloatField(default=0.0, verbose_name='hum')),
                ('altBar', models.FloatField(default=0.0, verbose_name='altBar')),
                ('pressure', models.FloatField(default=0.0, verbose_name='pressure')),
                ('NO2', models.FloatField(default=0.0)),
                ('CO', models.FloatField(default=0.0)),
                ('NH3', models.FloatField(default=0.0)),
                ('PM1_0', models.FloatField(default=0.0)),
                ('PM2_5', models.FloatField(default=0.0)),
                ('PM10_0', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'observation',
                'verbose_name_plural': 'observations',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('surname', models.CharField(max_length=50, verbose_name='surname')),
                ('dni', models.CharField(max_length=9, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('mail', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
    ]
