# Generated by Django 3.0.7 on 2020-07-07 13:42

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name='date_time')),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='geom')),
                ('altitude_gps', models.FloatField(default=0.0, verbose_name='altitude_gps')),
                ('temperature', models.FloatField(default=0.0, verbose_name='temperature')),
                ('humidity', models.FloatField(default=0.0, verbose_name='humidity')),
                ('altitude_bar', models.FloatField(default=0.0, verbose_name='altitude_bar')),
                ('pressure', models.FloatField(default=0.0, verbose_name='pressure')),
                ('no2', models.FloatField(default=0.0)),
                ('co', models.FloatField(default=0.0)),
                ('nh3', models.FloatField(default=0.0)),
                ('pm1_0', models.FloatField(default=0.0)),
                ('pm2_5', models.FloatField(default=0.0)),
                ('pm10_0', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'observation',
                'verbose_name_plural': 'observations',
            },
        ),
    ]
