version: '3.5'
services:
  postgis-diy:
    image: kartoza/postgis:10.0-2.4
    environment:
      POSTGRES_USER: cansat
      POSTGRES_PASS: mysecretpassword
      POSTGRES_DBNAME: cansat
    volumes:
      - ./data/postgresql:/var/lib/postgresql
    ports:
      - 5432
    networks:
      - network1
  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./data/www:/var/www
      - ./data/static:/static:ro
    ports:
      - 80:80
    networks:
      - network1
  django:
    image: geomatico/diysatellites
    command: sh /code/init_django.sh
    volumes:
    - ./data/static:/static
    expose:
    - 80
    networks:
      - network1
networks:
  network1:
    name: madrid-respira
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.198.0/24